export const projects = [
  {
    title: "Crownwize Consulting",
    longDescription: `A professional accounting, tax, and business advisory website built for Crownwize Consulting Ltd, a UK-based consultancy serving clients across the North East and throughout the UK.

    The project was designed to establish a credible and professional digital presence for the consultancy while making its accounting, tax, compliance, and business advisory services easy for prospective clients to understand. The experience combines a refined corporate visual identity with clear service structures, practical financial information, and conversion-focused calls to action.

    The website presents Crownwize Consulting's core services including bookkeeping, tax planning and filing, and business strategy. It also includes structured service packages, pricing information, client onboarding guidance, FAQs, a blog, reviews, legal and compliance information, and direct consultation and WhatsApp contact options.`,
    tech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Responsive Design",
      "Sanity CMS",
      "Custom Design System",
      "Content Management",
      "SEO",
      "Image Optimization",
      "Performance Optimization",
      "Accessibility",
    ],
    thumbnail: "/projects/project7.png",
    live: "https://crownwizeconsult.co.uk/",
    github: "https://github.com/lollykrown",
    year: "2026",
    role: "Frontend Developer",
    client: "Crownwize Consulting Ltd",
    duration: "2 weeks",
    features: [
      "Professional Corporate Website",
      "Accounting & Tax Service Pages",
      "Business Advisory Services",
      "Service Packages & Pricing",
      "Blog & Content Management",
      "FAQ Section",
      "Client Reviews",
      "Consultation Booking",
      "WhatsApp Integration",
      "Legal & Compliance Pages",
      "Responsive Design",
      "SEO Optimization",
      "Performance Optimization",
      "Accessibility",
    ],
  },
  {
    title: "BJ Media Production",
    longDescription: `A cinematic videography and film production website built for BJ Media Production, a Lagos-based visual storytelling studio focused on creating films for brands, businesses, weddings, events, and documentaries.

    The project was designed to position the production company as a premium visual storytelling partner rather than simply a video service provider. The experience puts the company's films and creative work at the centre of the website, using immersive imagery, cinematic typography, carefully structured case studies, and a refined editorial layout to communicate the quality and storytelling philosophy behind the work.

    The website presents BJ Media Production's core services including corporate films, brand films, commercial video, documentary filmmaking, wedding films, and event coverage, while also providing a clear process for prospective clients to discover, plan, produce, edit, and deliver their projects.`,
    tech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Responsive Design",
      "Video Integration",
      "YouTube Integration",
      "Cinematic Portfolio",
      "Custom Design System",
      "Image Optimization",
      "SEO",
      "Performance Optimization",
      "Accessibility",
    ],
    thumbnail: "/projects/project6.png",
    live: "https://bjmediaproduction.com",
    github: "https://github.com/lollykrown",
    year: "2026",
    role: "Frontend Developer",
    client: "BJ Media Production",
    duration: "1 week",
    features: [
      "Cinematic Portfolio Experience",
      "Video Portfolio Integration",
      "Corporate Film Showcase",
      "Documentary Film Showcase",
      "Wedding & Event Film Showcase",
      "Commercial Video Showcase",
      "Service & Deliverables Pages",
      "Project Case Studies",
      "Responsive Design",
      "SEO Optimization",
      "Performance Optimization",
    ],
  },
  {
    title: "Estandz Place Consulting",
    longDescription: `A full accounting and tax advisory website rebuilt from the ground up on Next.js, replacing a static site with a CMS-driven platform designed for real day-to-day content management by a non-technical client.
    I was responsible for the complete build — architecture, design system, and backend. This meant designing a distinctive "ledger" visual identity (perforated receipt-style cards, ruled lines, a warm ledger-green and mustard-gold palette) rather than a generic template look, then wiring it to a headless Sanity CMS so the client can publish blog posts, speaking engagements, downloadable resources, and client reviews without touching code. On the backend, I built transactional email infrastructure using Resend and React Email for the contact form, a full client-onboarding intake form, and gated resource downloads — each with server-side Zod validation, input sanitization, rate limiting, and bot-detection (honeypot fields plus submission-timing checks) to keep the forms genuinely spam-resistant in production.`,
    tech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Sanity CMS",
      "Figma to Code",
      "Resend",
      "React Email",
      "Zod Validation",
      "Rate Limiting",
      "Bot/Spam Protection",
      "GROQ Queries",
      "On-Demand Revalidation (ISR + Webhooks)",
      "Custom Design System",
      "Blog / Content Platform",
      "SEO & Structured Data",
      "Responsive Design",
    ],
    thumbnail: "/projects/project5.png",
    live: "https://www.estandzplaceconsulting.co.uk",
    github: "https://github.com/lollykrown/estandplace",
    year: "2026",
    role: "Full-stack Developer",
    client: "Estandz Place Consulting Ltd",
    duration: "3 weeks",
    features: [
      "Custom Ledger-Themed Design System",
      "Sanity CMS (Blog, Resources, Speaking Events, Reviews)",
      "Client Onboarding Intake Form",
      "Transactional Email System (Resend + React Email)",
      "Form Validation & Sanitization (Zod)",
      "Rate Limiting & Spam Protection",
      "Blog with Categories, Pagination & Related Posts",
      "SEO Optimization & Structured Data",
    ],
  },
  {
    title: "Tivitea Africa",
    longDescription: `The project focused on creating a dynamic, user-centric platform designed to 
      empower artisans—giving them seamless access to rentable workspaces and tools, while also 
      enabling them to showcase their skills and connect with potential clients.
      I was responsible for bringing the vision to life on the frontend—translating a comprehensive 
      Figma design system into a fully functional, responsive, and high-performance web experience. 
      This involved crafting reusable components, ensuring pixel-perfect implementation, 
      and delivering an intuitive interface that balances aesthetics with usability.`,
    tech: [
      "Next.js",
      "Tailwind CSS",
      "Authentication",'API Integration', 'Figma to Code',
      "REST API",
      "JWT Authentication",
      "Role-Based Access Control",
      "Dashboard UI (Charts & Tables)",
      "Payment Integration",
      "Booking System Logic",
      "Cloud Storage (Images)",
      "Server Actions / SSR",
      "Cookie-Based Sessions",
      "Responsive Design",
      "Performance Optimization",
      "SEO"
    ],
    github: "https://github.com/lollykrown",
    thumbnail: "/projects/project2.png",
    live: "https://tivitea.africa",
    year: "2023",
    role: "Full-stack Developer",
    client: "Tivitea Africa",
    duration: "6 weeks",
    features: ["Multi-User Roles System","Role-Based Dashboards", "Booking System", "Listings / Marketplace","Payments Integration",
      "Analytics & Charts", "User Reviews & Ratings","Authentication & Session System", "Comprehensive Admin Panel","Multi-Account Switching"],
  },
  {
    title: "Union Care Consult",
    longDescription: `A sleek, single-page website built for a small business to establish a strong and modern online presence.
    I transformed a Figma design into clean, production-ready code—starting with a solid HTML, CSS, and Bootstrap, then progressively enhancing the project by migrating it into a React-based architecture for improved scalability and maintainability. To elevate the visual experience, I integrated illustrations from unDraw, adding a polished and engaging touch to the overall design.`,
    tech: [
      "Next.js",
      "Bootstrap",
      'Figma to Code',
      "Illustration Integration (unDraw)",
      "CSS",
      "Contact Form Integration",
      "Basic SEO",
      "Responsive Design",
      "Google Maps Integration",
      "Performance Optimization"
    ],
    thumbnail: "/projects/project1.png",
    live: "https://unioncareconsult.com",
    github: "https://github.com/lollykrown",
    year: "2022",
    role: "Frontend Developer",
    client: "Union Care Consult",
    duration: "1 week",
    features: ["Core Purpose (Simple but focused)", "Basic Responsive Design", "SEO Foundations"],
  },
  {
    title: "Care Network International",
    longDescription: `The project was for a charity oganization, and the goal was to create a modern, user-friendly website that effectively communicates the organization’s mission, engages visitors, and encourages support and donations. 
    I was responsible for translating a comprehensive Figma design system into a fully functional, responsive, and high-performance web experience. This involved crafting reusable components, ensuring pixel-perfect implementation, 
    and delivering an intuitive interface that balances aesthetics with usability.`,
    tech: [
      "Next.js",
      "Tailwind CSS",
      'API Integration',
      'Figma to Code',
      'Authentication',
      "Donation Integration (gofundme)",
      "Campaign Pages",
      "Email Notifications",
      "Basic CMS (for content updates)",
      "Responsive Design",
      "SEO",
      "Analytics",
      "Performance Optimization",
    ],
    github: "https://github.com/lollykrown/careNet",
    thumbnail: "/projects/project3.png",
    live: "https://carenetwork.ngo",
    year: "2024",
    role: "Frontend Developer",
    client: "Care Network NGO",
    duration: "1 week",
    features: ["Mission-Driven Homepage", "Causes / Campaign System", "Donation System (Key Feature)",
      "Volunteer & Community Engagement","Awareness & Advocacy","News / Updates Section","Contact & Trust Signals" ],
  },
  {
    title: "Dashboard",
    description: "A powerful, highly customizable dashboard application built with Next.js and a modern ecosystem of supporting libraries, designed for scalability, performance, and a seamless user experience.",
    tech: [
      "Next.js",
      "Tailwind CSS",
      "Chart Libraries",
      "Responsive Design",
      "Component-Based Architecture",
      "Dark Mode Support",
      "Reusable UI Components",
      "State Management (React hooks)"
    ],
    github: "https://github.com/lollykrown",
    thumbnail: "/projects/project4.png",
    live: "https://robust-dashboard.netlify.app",
    year: "2024",
    role: "Full-stack Developer",
    client: "Care Network NGO",
    duration: "2 weeks",
    features: ["Admin Dashboard Layout", "Analytics & Charts", "Data Tables with Sorting & Pagination", 
      "User Management System", "Performance Optimization", "Responsive Design"],
  },
];

// ─── Categories ───────────────────────────────────────────────────
export const categories = [
  { id: "all",       label: "All Work" },
  { id: "portraits", label: "Portraits" },
  { id: "weddings",  label: "Weddings" },
  { id: "events",    label: "Events" },
  { id: "maternity",    label: "Maternity" },
  // { id: "editorial", label: "Editorial" },
  // { id: "nature",     label: "Nature" },
  // { id:"travel", label:"Travel" },
  // { id: "product",    label: "Product" },
  { id: "baby",      label: "Baby" },
  { id: "other",     label: "Other" },
];

// ─── Photo data ───────────────────────────────────────────────────
export const photos = [
  { id: 1,  category: "weddings",  src: "https://res.cloudinary.com/lollykrown/image/upload/v1775987390/photography/KAY_2447-Edit.jpg", alt: "Civil Wedding", aspectRatio: "wide", location: "City Hall,Sunderland, UK" },
  { id: 2,  category: "portraits", src: "https://res.cloudinary.com/lollykrown/image/upload/v1776007141/photography/0737.jpg", alt: "Studio Portrait", aspectRatio: "tall", location: "Lollykrown Studios, Sunderland, UK" },
  { id: 3,  category: "events",    src: "https://res.cloudinary.com/lollykrown/image/upload/v1775995918/photography/KAY_0505.jpg",    alt: "Birthday Celebrant's Dance", aspectRatio: "wide",   location: "Maya Suite, Sheffield, UK" },
  { id: 4,  category: "baby",      src: "https://res.cloudinary.com/lollykrown/image/upload/v1775988516/photography/KAY_8943-Edit.jpg", alt: "Newborn Baby Portrait", aspectRatio: "tall", location: "Lollykrown Studios, Sunderland, UK" },
  { id: 5,  category: "portraits", src: "https://res.cloudinary.com/lollykrown/image/upload/v1775987389/photography/KAY_2106-Edit.jpg", alt: "Sunset Portrait", aspectRatio: "tall", location: "Osaka Gardens, Sunderland, UK" },
  { id: 6,  category: "events",    src: "https://res.cloudinary.com/lollykrown/image/upload/v1775989009/photography/KAY_0805.jpg", alt: "Aso Ebi Ladies", aspectRatio: "wide", location: "Fedash Centre, Sunderland, UK" },
  { id: 7,  category: "maternity", src: "https://res.cloudinary.com/lollykrown/image/upload/v1776006164/photography/KAY_3868.jpg", alt: "Maternity Photoshoot", aspectRatio: "tall", location: "Mowbray Park, Sunderland, UK" },
  { id: 8,  category: "portraits", src: "https://res.cloudinary.com/lollykrown/image/upload/v1776007342/photography/KAY_7587.jpg", alt: "Birthday Portrait", aspectRatio: "tall", location: "Lezzet Restaurant, Newcastle, UK" },
  { id: 9,  category: "weddings",  src: "https://res.cloudinary.com/lollykrown/image/upload/v1775987389/photography/KAY_2369.jpg", alt: "Couple Portrait", aspectRatio: "wide",   location: "Brew & Bake, Sunderland, UK" },
  { id: 10, category: "maternity", src: "https://res.cloudinary.com/lollykrown/image/upload/v1776006161/photography/KAY_3783.jpg", alt: "Maternity Photoshoot", aspectRatio: "tall", location: "Mowbray Park, Sunderland, UK" },
  { id: 11, category: "events",    src: "https://res.cloudinary.com/lollykrown/image/upload/v1775995079/photography/KAY_1451.jpg", alt: "Birthday Celebrant's Dance", aspectRatio: "square", location: "Fedash Centre, Sunderland, UK" },
  { id: 12, category: "portraits", src: "https://res.cloudinary.com/lollykrown/image/upload/v1778356191/photography/KAY_0589-Edit.jpg", alt: "Studio Portrait", aspectRatio: "square", location: "Lollykrown Studios, Sunderland, UK" },
  { id: 13, category: "baby",      src: "https://res.cloudinary.com/lollykrown/image/upload/v1775988552/photography/KAY_8941.jpg", alt: "Newborn Baby Portrait",  aspectRatio: "square", location: "Lollykrown Studios, Sunderland, UK" },
  { id: 14, category: "portraits", src: "https://res.cloudinary.com/lollykrown/image/upload/v1776007341/photography/KAY_7604.jpg", alt: "Birthday Portrait",    aspectRatio: "tall",   location: "Lezzet Restaurant, Newcastle, UK" },
  { id: 15, category: "baby",      src: "https://res.cloudinary.com/lollykrown/image/upload/v1775988521/photography/KAY_9019-Edit.jpg", alt: "Newborn Baby Portrait",  aspectRatio: "square", location: "Lollykrown Studios, Sunderland, UK" },
  { id: 16, category: "events",    src: "https://res.cloudinary.com/lollykrown/image/upload/v1775987392/photography/KAY_5469.jpg", alt: "African Cultural Dance and Drama", aspectRatio: "wide", location: "Fedash Centre, Sunderland, UK" },
  { id: 17, category: "weddings",  src: "https://res.cloudinary.com/lollykrown/image/upload/v1776007195/photography/IMG_7011.jpg", alt: "Couple Photoshoot", aspectRatio: "square", location: "Heaton Park, Newcastle, UK" },
  { id: 18, category: "events",    src: "https://res.cloudinary.com/lollykrown/image/upload/v1776007340/photography/KAY_7539.jpg", alt: "Birthday Dinner", aspectRatio: "square", location: "Lezzet Restaurant, Newcastle, UK" },
  { id: 19, category: "portraits",    src: "https://res.cloudinary.com/lollykrown/image/upload/v1778356118/photography/KAY_0646-Edit-4.jpg", alt: "Studio Portrait", aspectRatio: "tall", location: "Lollykrown Studios, Sunderland, UK" },
  { id: 20, category: "maternity", src: "https://res.cloudinary.com/lollykrown/image/upload/v1776006168/photography/KAY_3867.jpg", alt: "Maternity Photoshoot",    aspectRatio: "tall",   location: "Mowbray Park, Sunderland, UK" },
  { id: 21, category: "events",    src: "https://res.cloudinary.com/lollykrown/image/upload/v1775995080/photography/KAY_0693.jpg",     alt: "Birthday dance",      aspectRatio: "tall",   location: "Seaham City Hall, Seaham, UK" },
  { id: 22, category: "portraits", src: "https://res.cloudinary.com/lollykrown/image/upload/v1778355977/photography/KAY_0547.jpg",     alt: "Studio Portrait",      aspectRatio: "tall",   location: "Lollykrown Studios, Sunderland, UK" },
  // { id: 17, category: "nature",    src: "/photos/nature-3.jpg",    alt: "Aurora over lake",          aspectRatio: "square", location: "Iceland" },
  // { id: 18, category: "editorial", src: "/photos/editorial-3.jpg", alt: "Street style editorial",    aspectRatio: "tall",   location: "Milan, Italy" },
  // { id: 19, category: "product",   src: "/photos/product-3.jpg",   alt: "Product photography",       aspectRatio: "square", location: "Berlin, Germany" },
  { id: 23, category: "baby",      src: "https://res.cloudinary.com/lollykrown/image/upload/v1775988554/photography/KAY_9055-Edit.jpg", alt: "Sleeping newborn", aspectRatio: "wide",   location: "Lollykrown Studios, Sunderland, UK" },
];

// Featured reviews — replace with real data / API
// export const allReviews = [
//   { id: 1, name: "Sophie & James",    role: "Wedding clients",              rating: 5, review: "The photos from our wedding day are beyond anything we could have imagined. Every emotion, every detail captured perfectly. We'll treasure these forever.",     date: "March 2025",    initials: "SJ" },
//   { id: 2, name: "Aria Mondelli",     role: "Creative Director, Lumène",   rating: 5, review: "Working with this photographer transformed our brand. The editorial series stopped people mid-scroll every time we posted. Truly exceptional creative vision.", date: "January 2025",  initials: "AM" },
//   { id: 3, name: "Marcus Chen",       role: "Events Manager, Soho House",  rating: 5, review: "The portraits from our event felt cinematic. Guests were speechless when they saw the gallery. Discreet, fast, and always in the right place at the right time.", date: "November 2024", initials: "MC" },
//   { id: 4, name: "Priya Nair",        role: "Founder, Bloom Studio",       rating: 5, review: "Our brand shoot was exactly what we needed. Clean, editorial, and completely on-brand. The turnaround was fast and the quality was incredible.",                 date: "October 2024",  initials: "PN" },
//   { id: 5, name: "Tom Whitfield",     role: "Head of Marketing, Kinetic",  rating: 4, review: "Professional, creative and easy to work with. The campaign images exceeded our expectations and have been used across all our channels.",                        date: "September 2024", initials: "TW" },
//   { id: 6, name: "Léa Fontaine",      role: "Portrait client",             rating: 5, review: "I was nervous about having my portrait taken but the session was relaxed and fun. The final images are genuinely the best photos ever taken of me.",             date: "August 2024",   initials: "LF" },
//   { id: 7, name: "Daniel Osei",       role: "CEO, Osei Ventures",          rating: 5, review: "Used for a corporate headshot session for our whole team. Every single person was happy with their photos — which never happens. Highly recommend.",             date: "July 2024",     initials: "DO" },
//   { id: 8, name: "Hannah & Rob",      role: "Wedding clients",              rating: 5, review: "From the first call to the final gallery, the experience was seamless. The ability to capture candid moments without anyone noticing is a real skill.",          date: "June 2024",     initials: "HR" },
//   { id: 9, name: "Cleo Marchetti",    role: "Fashion Editor, VIVA",        rating: 5, review: "One of the few photographers who truly understands light and movement in a fashion context. A pleasure to collaborate with on editorial shoots.",               date: "May 2024",      initials: "CM" },
// ];

export const allReviews = [
  { id: 1, name: "Aria Mondelli",     role: "Founder, Lumène",             rating: 5, review: "Delivered our entire SaaS dashboard in four weeks — clean code, pixel-perfect UI, and zero bugs on launch. The best freelance dev we've ever hired.",          date: "March 2025",     initials: "AM" },
  { id: 2, name: "Marcus Chen",       role: "CTO, Soho Ventures",          rating: 5, review: "Took our messy legacy codebase and refactored it into something we're actually proud of. Communication was excellent throughout and deadlines were always hit.",  date: "February 2025",  initials: "MC" },
  { id: 3, name: "Priya Nair",        role: "Founder, Bloom Studio",       rating: 5, review: "Built our entire e-commerce platform from scratch — Next.js, Stripe, custom CMS. It's fast, beautiful, and our conversion rate jumped 40% after launch.",       date: "January 2025",   initials: "PN" },
  { id: 4, name: "Tom Whitfield",     role: "Head of Product, Kinetic",    rating: 4, review: "Excellent work on our React Native app. The code quality is superb and the attention to performance optimisation made a noticeable difference in user retention.", date: "December 2024",  initials: "TW" },
  { id: 5, name: "Léa Fontaine",      role: "CEO, Studio Nord",            rating: 5, review: "Our website went from an embarrassment to our best sales tool. The redesign and rebuild was handled end-to-end — design, dev, SEO. Outstanding result.",          date: "November 2024",  initials: "LF" },
  { id: 6, name: "Daniel Osei",       role: "CTO, Osei Ventures",          rating: 5, review: "We needed a complex API integration done properly under tight deadlines. Delivered early, documented thoroughly, and explained every decision clearly.",           date: "October 2024",   initials: "DO" },
  { id: 7, name: "Hannah Brooks",     role: "Product Manager, Waverly",    rating: 5, review: "The Framer Motion animations and interactions on our marketing site generated more compliments from clients than anything else we've shipped. Incredible work.",    date: "September 2024", initials: "HB" },
  { id: 8, name: "James Okafor",      role: "Founder, Stackly",            rating: 5, review: "Rebuilt our onboarding flow in TypeScript and cut drop-off by 30%. Knows how to balance speed with quality and always brings solutions, not just problems.",       date: "August 2024",    initials: "JO" },
  { id: 9, name: "Cleo Marchetti",    role: "Design Lead, Forma",          rating: 5, review: "Rare to find a developer who truly understands design. Every component was built exactly to spec, responsive across all devices, and the code is a joy to read.", date: "July 2024",      initials: "CM" },
];